### ISSUE TITLE
enigma crashes with 0.84

### ISSUE THREAD

**Issue by githubrsys** [su1s/e2m3u2bouquet#113]
It is a newnigma2 on latest daily builds. DM820
```
I/  [isUpdateRequired] :: /usr/sbin/flash-fsbl
I/  [FSBLUpdateHandler.check] :: No FSBL update required!
[e2m3u2b] autostart 0 occured at 1571848451.97
EXCEPTION IN PYTHON STARTUP CODE:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 828, in <module>
    runScreenTest()
  File "/usr/lib/enigma2/python/mytest.py", line 616, in runScreenTest
    session = Session(desktop = getDesktop(0), summary_desktop = getDesktop(1), navigation = nav)
  File "/usr/lib/enigma2/python/mytest.py", line 305, in __init__
    p(reason=0, session=self)
  File "/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/plugin.py", line 320, in autostart
  File "/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/plugin.py", line 83, in __init__
AttributeError: 'eTimer' object has no attribute 'callback'
------------------------------------------------------------
(exit code 5)
```

**Comment by DougMac** [comment]
Thanks for the bug report.

I'll look into it.

**Comment by DougMac** [comment]
Are you able the attached version?
[enigma2-plugin-extensions-e2m3u2bouquet_0.8.4-b0_all.ipk.zip](https://github.com/su1s/e2m3u2bouquet/files/3764209/enigma2-plugin-extensions-e2m3u2bouquet_0.8.4-b0_all.ipk.zip)

**Comment by githubrsys** [comment]
Hi, this works. Thanks for that. 

Unfortunately it seems, that if I force the ipk installation on a newnigma2 (which shall use deb packages if I remember correct) the executable is not in place. A query with `which e2m3u2bouquet.py` gives no response. But the plugin does appear in the plugin manager menu.

```dpkg -i /tmp/enigma*
(Reading database ... 15139 files and directories currently installed.)
Preparing to unpack .../enigma2-plugin-extensions-e2m3u2bouquet_0.8.4-b0_all.ipk ...

********************************************
Installing Engima2 IPTV E2m3u2bouquet plugin
********************************************

Unpacking enigma2-plugin-extensions-e2m3u2bouquet (0.8.4-b0) over (0.8.4-b0) ...
********************************************
Removing IPTV bouquets
********************************************


********************************************
Removing files
********************************************

find: /etc/epgimport/: No such file or directory

********************************************
Engima2 IPTV E2m3u2bouquet plugin uninstalled
********************************************

********************************************
Restart box to complete uninstall
********************************************
Setting up enigma2-plugin-extensions-e2m3u2bouquet (0.8.4-b0) ...

********************************************
Engima2 IPTV E2m3u2bouquet plugin installed
********************************************

********************************************
Restart box to complete install
```


```
root@dm820:/home$ opkg list-installed | grep bouquet
enigma2-plugin-extensions-c3vocupdater - 4.3.2+git121+2791d6bd44-r0.0 - c3voc stream bouquet updater
enigma2-plugin-extensions-e2m3u2bouquet - 0.8.4-b0 - Multi Provider IPTV Bouquet Maker For Enigma2
enigma2-plugin-extensions-webbouqueteditor - 4.3.2+git121+2791d6bd44-r0.0 - Extension for enigma2 webinterface to sort bouquets and other

```

```
find / | grep e2m3u2bouquet
/var/lib/dpkg/info/enigma2-plugin-extensions-e2m3u2bouquet.postinst
/var/lib/dpkg/info/enigma2-plugin-extensions-e2m3u2bouquet.postrm
/var/lib/dpkg/info/enigma2-plugin-extensions-e2m3u2bouquet.preinst
/var/lib/dpkg/info/enigma2-plugin-extensions-e2m3u2bouquet.list
/var/lib/dpkg/info/enigma2-plugin-extensions-e2m3u2bouquet.md5sums
/etc/enigma2/e2m3u2bouquet
/etc/enigma2/e2m3u2bouquet/config.xml
/autofs/sda1/._enigma2-plugin-extensions-e2m3u2bouquet_0.8.4-b0_all.ipk
/autofs/sda1/enigma2-plugin-extensions-e2m3u2bouquet_0.8.4-b0_all.ipk
/tmp/e2m3u2bouquet
/tmp/enigma2-plugin-extensions-e2m3u2bouquet_0.8.4-b0_all.ipk
/mnt/nfs/public/enigma2-plugin-extensions-e2m3u2bouquet_0.8.2_all.ipk
/media/hdd/._enigma2-plugin-extensions-e2m3u2bouquet_0.8.4-b0_all.ipk
/media/hdd/enigma2-plugin-extensions-e2m3u2bouquet_0.8.4-b0_all.ipk
```

```
root@dm820:/usr/lib/enigma2/python/Plugins/Extensions$ ls -la
drwxr-xr-x   26 root     root          4096 Oct 28 13:59 .
drwxr-xr-x    8 root     root          4096 Sep 30 10:10 ..
drwxr-xr-x    3 root     root          4096 Oct 23 17:39 AudioSync
drwxr-xr-x    7 root     root         12288 Oct 23 17:39 AutoTimer
drwxr-xr-x    2 root     root          4096 Oct 23 17:39 Bonjour
drwxr-xr-x    2 root     root          4096 Sep 29 20:39 Browser
drwxr-xr-x    2 root     root          4096 Sep 29 20:39 CutListEditor
drwxr-xr-x    3 root     root          4096 Oct 23 17:39 EPGRefresh
drwxr-xr-x    2 root     root          4096 Oct 23 17:39 GenuineDreambox
drwxr-xr-x    2 root     root          4096 Sep 29 20:39 GraphMultiEPG
drwxr-xr-x    2 root     root          4096 Sep 29 20:39 HbbTV
drwxr-xr-x    3 root     root         12288 Sep 29 20:39 MediaCenter
drwxr-xr-x    2 root     root          4096 Sep 29 20:39 MediaPlayer
drwxr-xr-x    2 root     root          4096 Sep 29 20:39 MediaRenderer
drwxr-xr-x    2 root     root          4096 Sep 29 20:39 MediaScanner
drwxr-xr-x    4 root     root          4096 Oct 23 17:39 PiconManager
drwxr-xr-x    2 root     root          4096 Sep 29 20:39 PicturePlayer
drwxr-xr-x    2 root     root          4096 Oct 23 17:39 Quickbutton
drwxr-xr-x    2 root     root          4096 Sep 29 20:39 SocketMMI
drwxr-xr-x    2 root     root          4096 Oct 23 17:39 StartupToStandby
drwxr-xr-x    2 root     root          4096 Oct 23 17:39 TeleText
drwxr-xr-x    4 root     root          4096 Oct 23 17:39 WeatherPlugin
drwxr-xr-x    7 root     root          4096 Oct 23 17:39 WebBouquetEditor
drwxr-xr-x   10 root     root          4096 Oct 23 17:39 WebInterface
drwxr-xr-x    2 root     root          4096 Oct 23 17:39 WerbeZapper
-rw-r--r--    1 root     root             0 Aug 30 23:13 __init__.py
-rw-r--r--    1 root     root           141 Aug 30 23:13 __init__.pyc
-rw-r--r--    1 root     root           141 Aug 30 23:13 __init__.pyo
drwxr-xr-x    2 root     root          4096 Oct 23 17:39 c3vocupdater
```
