### ISSUE TITLE
Update on boot (plugin)

### ISSUE THREAD

**Issue by davesayers2014** [su1s/e2m3u2bouquet#43]
My provider was having server issues. When I rebooted box my box stopped on loading with the spinner and I couldn’t get past boot. I think this is because it was set to update on boot could we have a try and exept for update on boot?

I did manage to get out of boot by deleting the plugin folder. 

Managed to create a debug log via talnet. 

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring
    
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 671, in disconnectAll
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    
  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/usr/lib/python2.7/site-packages/twisted/internet/unix.py", line 420, in connectionLost
    
exceptions.OSError: [Errno 2] No such file or directory: '/tmp/hotplug.socket'

**Comment by DougMac** [comment]
This plugin does nothing on boot.

**Comment by davesayers2014** [comment]
Sorry I thought this was it config.plugins.e2m3u2b.autobouquetupdateatboot = ConfigYesNo(default=True)

Although I dont see an option in the plugin menu?

**Comment by DougMac** [comment]
Where do you see 'config.plugins.e2m3u2b.autobouquetupdateatboot = ConfigYesNo(default=True)'?

autobouquetupdateatboot is set to false by default with no option to change the value.

**Comment by davesayers2014** [comment]
I changed it within the plugin.py thinking it would help running on boot I'll change it back to false.

**Comment by DougMac** [comment]
It was left disabled (with no option to enabled) as it wasn't fully tested and we didn't want the plugin killing the box on boot.
