### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by bbbuk** [su1s/e2m3u2bouquet#46]
Hi, got following unhandled exception which resulted in crash and reboot.  Would be nice if this was handled maybe via just an error message!

```
----Downloading providers file----<288172.362> 
<288172.589> 
----Downloading providers bouquet file----<288172.589> 
<288176.021> [gRC] main thread is non-idle! display spinner!
<288222.654> Traceback (most recent call last):
<288222.654>   File "/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/plugin.py", line 303, in on_timer
<288222.664>   File "/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/plugin.py", line 335, in do_update
<288222.664>   File "/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/e2m3u2bouquet.py", line 1128, in main
<288222.666>   File "/usr/lib/enigma2/python/Plugins/Extensions/E2m3u2bouquet/e2m3u2bouquet.py", line 145, in download_bouquet
<288222.667> IOError: [Errno socket error] timed out
<288222.667> [ePyObject] (CallObject(<bound method AutoStartTimer.on_timer of <Plugins.Extensions.E2m3u2bouquet.plugin.AutoStartTimer instance at 0x63cb9490>>,()) failed)

```
Thanks for all your hard work on this.  It's an excellent plugin.

**Comment by DougMac** [comment]
Thanks for the error report.

I'll put a catch in for the error so that it's logged (instead of crashing the box).

I take it you only get this error intermittently?

**Comment by bbbuk** [comment]
Yes.  The IPTV provider was down so it crashed.  Other than that, it's been excellent plugin.  Thank you.

**Comment by DougMac** [comment]
Hopefully fixed in next plugin release

**Comment by bbbuk** [comment]
Thank you
